import './globals.css'
import { Inter } from 'next/font/google'
import Theme from './theme_config'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Enoch's Portfolio",
  description: 'Generated by Create Next App',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
